#    pub_leash.example:
#        class: PubLeashBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
  geo_reader:
    class: GeoIp2\Database\Reader
    arguments: ["%kernel.root_dir%/../src/PubLeashBundle/Resources/geoip-db/GeoLite2-Country.mmdb", ["en"]]

  geoip:
    class: PubLeashBundle\Service\GeoIP
#    scope: request
    autowire: true

  publication:
    class: PubLeashBundle\Service\Publication
    autowire: true

  review:
    class: PubLeashBundle\Service\Review
    autowire: true

  author:
    class: PubLeashBundle\Service\Author
    autowire: true

  notification:
    class: PubLeashBundle\Service\Notification
