#    pub_leash.example:
#        class: PubLeashBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
  geo_reader:
    class: GeoIp2\Database\Reader
    arguments: ["%kernel.root_dir%/../src/PubLeashBundle/Resources/geoip-db/GeoLite2-Country.mmdb", ["en"]]

  geoip:
    class: PubLeashBundle\Service\GeoIP
#    scope: request
    autowire: true

  publication:
    class: PubLeashBundle\Service\Publication
    autowire: true

  review:
    class: PubLeashBundle\Service\Review
    autowire: true

  author:
    class: PubLeashBundle\Service\Author
    autowire: true

  notification:
    class: PubLeashBundle\Service\Notification

  api:
    class: PubLeashBundle\Service\Api
    autowire: true

  api_chapter:
    class: PubLeashBundle\Service\ApiChapter
    arguments: ['@doctrine.orm.default_entity_manager']
    tags:
      - { name: api.service }

  api_publication:
      class: PubLeashBundle\Service\ApiPublication
      arguments: ['@doctrine.orm.default_entity_manager']
      tags:
        - { name: api.service }

  api_notification:
        class: PubLeashBundle\Service\ApiNotification
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
          - { name: api.service }

  api_library:
          class: PubLeashBundle\Service\ApiLibrary
          arguments: ['@doctrine.orm.default_entity_manager']
          tags:
            - { name: api.service }

  api_review:
            class: PubLeashBundle\Service\ApiReview
            arguments: ['@twig', '@doctrine.orm.default_entity_manager']
            tags:
              - { name: api.service }

  library:
    class: PubLeashBundle\Service\Library
    autowire: true
