imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PubLeashBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@PubLeashBundle/Resources/config/parameters.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
          - 'PubLeashBundle:Form:bootstrap3-form-types.html.twig'
#           - 'bootstrap_3_layout.html.twig'
    globals:
      publication_service: '@publication'
      review_service: '@review'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: PubLeashBundle\Entity\User
    from_email:
                address:  'registrator@publeash.nightnr.com'
                sender_name:  'PubLeash - Registrator'
    registration:
      confirmation:
        enabled: true
      form:
        type: UserBundle\Form\Type\RegistrationFormType
    profile:
      form:
        type: UserBundle\Form\Type\ProfileFormType

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        lessphp:
                file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
                apply_to: \.less$
        cssrewrite: ~
    assets:
            bootstrap_css:
                inputs:
                    - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css'
                    - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css'
                filters:
                    - lessphp
                    - cssrewrite
                output: 'css/bootstrap.css'
            bootstrap_js:
                inputs:
                    - '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js'
                output: 'js/bootstrap.js'
            bootstrap_fonts_woff:
                        inputs:
                            - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff'
                        output: fonts/glyphicons-halflings-regular.woff
            bootstrap_fonts_woff2:
                                    inputs:
                                        - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff2'
                                    output: fonts/glyphicons-halflings-regular.woff2
            bootstrap_fonts_ttf:
                        inputs:
                            - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf'
                        output: fonts/glyphicons-halflings-regular.ttf
            bootstrap_fonts_svg:
                        inputs:
                            - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg'
                        output: fonts/glyphicons-halflings-regular.svg
            bootstrap_fonts_eot:
                        inputs:
                            - '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot'
                        output: fonts/glyphicons-halflings-regular.eot

ewz_recaptcha:
    public_key:  '6LewGxoTAAAAAIxPJAzMOOHYmKN_wsk-Embtzmmq'
    private_key: '6LewGxoTAAAAALExCdi4h6434w3WEe6ejCYhWlO0'
    locale_key:  %kernel.default_locale%

ornicar_gravatar:
  rating: g
  size: 80
  default: mm

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig


kms_froala_editor:
    language: "en"
    height: 500
    pluginsDisabled: [ "save" ]