<?php

namespace PubLeashBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageEnumRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LanguageEnumRepository extends EntityRepository
{
}
